# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1995cb85c80ce7756042356ba454fc10d82df3e9bd261d117c94f728f7bbddac2e29a8ccd4b2b7115dff9c96ed62b049040f76421808d8138894806ec7d33a9

test:
  secret_key_base: 67ef93c4e91efb2e3e8e20a7a3ead648bdcbeaf49974139255fade6cd95d7af208002dea606aa65ba608d3d117d5c3efa4d2f397e38d7ebdf69cd88dc64f6522

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
